routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

# Tasks Routes
Route::resource('tasks', 'TasksController')->middleware('auth');
Route::get('tasks/changestatus/{id}/{sid}', 'TasksController@changeStatus')->name('tasks.changestatus');

Route::get('tasks/delete/{id}', 'TasksController@destroy')->name('tasks.delete');

Route::get('tasks/changeuser/{tid}/{uid?}', 'TasksController@changeUser')->name('task.changeuser');

Route::get('mytasks', 'TasksController@myTasks')->name('tasks.mytasks')->middleware('auth');

Route::get('completedtasks', 'TasksController@completedTasks')->name('tasks.completedtasks')->middleware('auth');


# Tools Routes
Route::resource('tools', 'ToolsController')->middleware('auth');

Route::get('tools/changeuser/{tl_id}/{uid?}', 'ToolsController@changeUser')->name('tools.changeuser');

Route::get('tools/delete/{id}', 'ToolsController@destroy')->name('tools.delete');




# Laravel Routes
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

resources/views/layouts/navbars/navbar.blade.php
@auth()
    @include('layouts.navbars.navs.auth')
@endauth
    
@guest()
    @include('layouts.navbars.navs.guest')
@endguest

resources/views/layouts/navbars/sidebar.blade.php
<nav class="navbar navbar-vertical fixed-left navbar-expand-md navbar-light bg-white" id="sidenav-main">
    <div class="container-fluid">
        <!-- Toggler -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#sidenav-collapse-main" aria-controls="sidenav-main" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <!-- Brand -->
        
        <a class="navbar-brand pt-0" href="{{ route('home') }}">
        <span class="avatar avatar-sm rounded-circle">
            <img alt="Image placeholder" src="{{ asset('argon') }}/img/theme/team-4-800x800.jpg">
        </span>
            <p>{{ auth()->user()->name }}</p>
            



        </a>
       
        <!-- Collapse -->
        <div class="collapse navbar-collapse" id="sidenav-collapse-main">
            <!-- Collapse header -->
            <div class="navbar-collapse-header d-md-none">
                <div class="row">
                    <div class="col-6 collapse-brand">
                        <a href="{{ route('home') }}">
                            <img src="{{ asset('argon') }}/img/brand/blue.png">
                        </a>
                    </div>
                    <div class="col-6 collapse-close">
                        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#sidenav-collapse-main" aria-controls="sidenav-main" aria-expanded="false" aria-label="Toggle sidenav">
                            <span></span>
                            <span></span>
                        </button>
                    </div>
                </div>
            </div>
            <!-- Form -->
            <form class="mt-4 mb-3 d-md-none">
                <div class="input-group input-group-rounded input-group-merge">
                    <input type="search" class="form-control form-control-rounded form-control-prepended" placeholder="{{ __('Search') }}" aria-label="Search">
                    <div class="input-group-prepend">
                        <div class="input-group-text">
                            <span class="fa fa-search"></span>
                        </div>
                    </div>
                </div>
            </form>
            <!-- Navigation -->
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('home') }}">
                        <i class="ni ni-tv-2 text-primary"></i> {{ __('Dashboard') }}
                    </a>
                </li>
                
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('tasks.index') }}">
                        <i class="ni ni-calendar-grid-58 text-primary"></i> {{ __('Tasks') }}
                    </a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{{ route('tasks.mytasks') }}">
                    <i class="fas fa-envelope-square"></i></i> {{ __('My Tasks') }}
                    </a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="#">
                    <i class="fas fa-tasks"></i> {{ __('Tools') }}
                    </a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{{ route('tasks.completedtasks') }}">
                        <i class="ni ni-circle-08 text-primary"></i> {{ __('Completed Tasks') }}
                    </a>
                </li>
                
                
                
                <li class="nav-item">
                    <a class="nav-link " href="#navbar-examples" data-toggle="collapse" role="button" aria-expanded="true" aria-controls="navbar-examples">
                        <i class="ni ni-settings-gear-65" ></i>
                        <span class="nav-link-text" >{{ __('Settings') }}</span>
                    </a>

                    <div class="collapse show" id="navbar-examples">
                        <ul class="nav nav-sm flex-column">
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('profile.edit') }}">
                                    {{ __('User Profile') }}
                                </a>
                            </li>
                            @can('admin') <li class="nav-item">
                                <a class="nav-link" href="{{ route('user.index') }}">
                                    {{ __('User Management') }}
                                </a>
                            </li> 
                            @endcan
                        </ul>
                    </div>
                    <div class="dropdown-divider"></div>
                    <a href="{{ route('logout') }}" class="dropdown-item" onclick="event.preventDefault();
                    document.getElementById('logout-form').submit();">
                        <i class="ni ni-key-25"></i>
                        <span>{{ __('Logout') }}</span>
                    </a>
                </div>
                </li>
            </ul>
           
        </div>
    </div>
</nav>